-- Generated by the Torrance Watch publisher, which applies this DDL to the
-- Neon database before each publish run. Generated 2026-09-08; hand edits here
-- are not applied to the database and are lost on the next generation.

-- A view pins the types of the columns beneath it; drop it before the tables
-- are altered and rebuild it after.
DROP VIEW IF EXISTS meetings.v_votes;

CREATE SCHEMA IF NOT EXISTS meetings;

-- ── bodies: the registry every other table scopes to ──────────────────────
CREATE TABLE IF NOT EXISTS meetings.bodies (
  body_slug        text PRIMARY KEY,
  name             text NOT NULL,
  body_kind        text NOT NULL,
  granicus_view_id integer,
  seat_count       integer,
  is_active        boolean NOT NULL DEFAULT true,
  created_at       timestamptz
);

-- ── members: the people the clerk's labels resolve to ─────────────────────
-- Identity only. No email, no phone, no address, no voter linkage: a reader
-- needs to know that "Councilmember Sheikh" and person 5745 are the same
-- person, and nothing else about them.
CREATE TABLE IF NOT EXISTS meetings.members (
  person_id      bigint PRIMARY KEY,
  canonical_name text   NOT NULL,
  clerk_labels   text[] NOT NULL DEFAULT '{}'
);

-- ── meetings ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS meetings.meetings (
  meeting_id           bigint PRIMARY KEY,
  body_slug            text NOT NULL REFERENCES meetings.bodies(body_slug) ON DELETE NO ACTION,
  meeting_kind         text NOT NULL,
  meeting_date         date NOT NULL,
  started_at           timestamptz,
  title                text NOT NULL,
  duration_seconds     integer,
  closed_session_spans jsonb NOT NULL DEFAULT '[]'::jsonb,
  granicus_clip_id     integer,
  primegov_meeting_id  integer,
  video_url            text,
  created_at           timestamptz,
  updated_at           timestamptz
);
-- Columns the laptop grew after this table first shipped. CREATE TABLE IF NOT
-- EXISTS will not alter an existing table, so every later column arrives as
-- its own idempotent ALTER and this list only grows.
ALTER TABLE meetings.meetings ADD COLUMN IF NOT EXISTS roll_calls jsonb NOT NULL DEFAULT '[]'::jsonb;

CREATE UNIQUE INDEX IF NOT EXISTS meetings_body_date_kind_uidx
  ON meetings.meetings (body_slug, meeting_date, meeting_kind);
CREATE INDEX IF NOT EXISTS meetings_body_date_idx
  ON meetings.meetings (body_slug, meeting_date DESC);

-- ── agenda items ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS meetings.agenda_items (
  agenda_item_id       bigint PRIMARY KEY,
  meeting_id           bigint  NOT NULL REFERENCES meetings.meetings(meeting_id) ON DELETE NO ACTION,
  granicus_meta_id     integer NOT NULL,
  ord                  integer NOT NULL,
  item_number          text,
  section_title        text,
  section_kind         text,
  title                text    NOT NULL,
  video_offset_seconds integer,
  -- Soft: self-referential inside a single rebuild, so a real FK would order
  -- the prune of this table against itself.
  parent_item_id       bigint,
  -- Soft: public_site.issue_master_groupings is not published.
  issue_grouping_slug  text
);
ALTER TABLE meetings.agenda_items ADD COLUMN IF NOT EXISTS end_offset_seconds integer;
ALTER TABLE meetings.agenda_items ADD COLUMN IF NOT EXISTS depth smallint;
ALTER TABLE meetings.agenda_items ADD COLUMN IF NOT EXISTS is_closed_session boolean NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS agenda_items_meeting_meta_uidx
  ON meetings.agenda_items (meeting_id, granicus_meta_id);
CREATE INDEX IF NOT EXISTS agenda_items_meeting_ord_idx
  ON meetings.agenda_items (meeting_id, ord);

-- ── item identifiers ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS meetings.item_identifiers (
  identifier_id   bigint PRIMARY KEY,
  agenda_item_id  bigint NOT NULL REFERENCES meetings.agenda_items(agenda_item_id) ON DELETE NO ACTION,
  id_type         text   NOT NULL,
  canonical_value text   NOT NULL,
  display_value   text   NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS item_identifiers_key_uidx
  ON meetings.item_identifiers (agenda_item_id, id_type, canonical_value);
CREATE INDEX IF NOT EXISTS item_identifiers_lookup_idx
  ON meetings.item_identifiers (id_type, canonical_value);

-- ── motions ───────────────────────────────────────────────────────────────
-- moved_by / seconded_by are the clerk's verbatim strings and are the
-- evidence; the *_person_id columns beside them are derived and rebuilt.
CREATE TABLE IF NOT EXISTS meetings.motions (
  motion_id             bigint PRIMARY KEY,
  meeting_id            bigint  NOT NULL REFERENCES meetings.meetings(meeting_id) ON DELETE NO ACTION,
  agenda_item_id        bigint  REFERENCES meetings.agenda_items(agenda_item_id) ON DELETE NO ACTION,
  granicus_meta_id      integer NOT NULL,
  motion_text           text    NOT NULL,
  motion_verb           text,
  motion_class          text,
  moved_by              text,
  moved_by_person_id    bigint  REFERENCES meetings.members(person_id) ON DELETE NO ACTION,
  seconded_by           text,
  seconded_by_person_id bigint  REFERENCES meetings.members(person_id) ON DELETE NO ACTION,
  outcome               text,
  video_offset_seconds  integer
);
-- The clerk's index entry that carries the OUTCOME of this motion, as opposed
-- to granicus_meta_id, which is the motion itself. Added after the table first
-- shipped, so it arrives as its own idempotent ALTER.
ALTER TABLE meetings.motions ADD COLUMN IF NOT EXISTS outcome_meta_id integer;

CREATE UNIQUE INDEX IF NOT EXISTS motions_meeting_meta_uidx
  ON meetings.motions (meeting_id, granicus_meta_id);
CREATE INDEX IF NOT EXISTS motions_item_idx
  ON meetings.motions (agenda_item_id) WHERE agenda_item_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS motions_class_idx
  ON meetings.motions (motion_class, motion_verb);

-- ── votes ─────────────────────────────────────────────────────────────────
-- A row means "recorded on the panel". A NULL vote_value means "recorded,
-- value not published", which is not the same as unknown and neither is the
-- same as absent; vote_value_source says where a recovered value came from.
CREATE TABLE IF NOT EXISTS meetings.votes (
  vote_id           bigint PRIMARY KEY,
  motion_id         bigint NOT NULL REFERENCES meetings.motions(motion_id) ON DELETE NO ACTION,
  member_name       text   NOT NULL,
  vote_value        text,
  vote_value_source text,
  person_id         bigint REFERENCES meetings.members(person_id) ON DELETE NO ACTION
);
CREATE UNIQUE INDEX IF NOT EXISTS votes_motion_member_uidx
  ON meetings.votes (motion_id, member_name);
CREATE INDEX IF NOT EXISTS votes_person_idx
  ON meetings.votes (person_id) WHERE person_id IS NOT NULL;

-- ── seats: the time-varying roster ────────────────────────────────────────
-- Half-open bounds with NULL meaning unbounded. A NULL valid_from means the
-- evidence window starts later than the seat did, never that the seat began
-- at an unknown date.
CREATE TABLE IF NOT EXISTS meetings.seats (
  person_id    bigint NOT NULL REFERENCES meetings.members(person_id) ON DELETE NO ACTION,
  body_slug    text   REFERENCES meetings.bodies(body_slug) ON DELETE NO ACTION,
  role         text   NOT NULL,
  jurisdiction text,
  valid_from   date,
  valid_to     date,
  source_ref   text
);
CREATE UNIQUE INDEX IF NOT EXISTS seats_key_uidx
  ON meetings.seats (person_id, body_slug, role, valid_from) NULLS NOT DISTINCT;

-- ── artifacts: the provenance ledger ──────────────────────────────────────
-- No local file-path column: it names a directory on one laptop, so it is
-- noise to every reader of this schema. The archive it points at is not
-- published either.
CREATE TABLE IF NOT EXISTS meetings.artifacts (
  artifact_id   bigint PRIMARY KEY,
  meeting_id    bigint REFERENCES meetings.meetings(meeting_id) ON DELETE NO ACTION,
  artifact_kind text        NOT NULL,
  source_url    text        NOT NULL,
  sha256        text        NOT NULL,
  byte_size     bigint,
  content_type  text,
  http_status   integer,
  fetched_at    timestamptz NOT NULL,
  -- Soft: the supersession chain points inside this same table.
  superseded_by bigint
);
CREATE INDEX IF NOT EXISTS artifacts_meeting_idx
  ON meetings.artifacts (meeting_id);
CREATE INDEX IF NOT EXISTS artifacts_current_idx
  ON meetings.artifacts (meeting_id, artifact_kind) WHERE superseded_by IS NULL;

-- ── publish_runs: the ledger ──────────────────────────────────────────────
-- One row per applied run, written inside the publish transaction so a
-- rolled-back publish leaves no claim that it happened.
CREATE TABLE IF NOT EXISTS meetings.publish_runs (
  run_id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  started_at     timestamptz NOT NULL,
  finished_at    timestamptz NOT NULL DEFAULT now(),
  mode           text        NOT NULL,
  laptop_git_sha text,
  brake_tripped  boolean     NOT NULL DEFAULT false,
  force_reason   text,
  counts         jsonb       NOT NULL DEFAULT '{}'::jsonb
);

-- ── The one view ──────────────────────────────────────────────────────────
-- Every join is LEFT: votes.person_id is null until the roster resolves a
-- clerk label, and motions.agenda_item_id is null for a motion the clerk
-- filed under no item. An INNER join would silently drop exactly the rows a
-- reader is most likely to be checking on.
--
-- member_name is the clerk's label from the vote row itself, never a value
-- reconstructed from members.clerk_labels: the vote table is unique on
-- (motion_id, member_name), so the label IS the identity of the panel row.
--
-- One view, and no summary views. A pre-aggregated count would freeze one
-- question's shape, and a reader with SQL can ask their own.
CREATE VIEW meetings.v_votes AS
SELECT b.body_slug,
       m.meeting_date,
       ai.item_number,
       ai.title,
       mo.motion_text,
       mo.motion_class,
       mo.outcome,
       v.member_name,
       mem.canonical_name,
       v.vote_value,
       v.vote_value_source,
       v.person_id
  FROM meetings.votes v
  LEFT JOIN meetings.motions      mo  ON mo.motion_id = v.motion_id
  LEFT JOIN meetings.agenda_items ai  ON ai.agenda_item_id = mo.agenda_item_id
  LEFT JOIN meetings.meetings     m   ON m.meeting_id = mo.meeting_id
  LEFT JOIN meetings.bodies       b   ON b.body_slug = m.body_slug
  LEFT JOIN meetings.members      mem ON mem.person_id = v.person_id;

-- ── Reader role ───────────────────────────────────────────────────────────
-- A login role with SELECT on this schema and nothing anywhere else. Its
-- password is NOT set here: a credential belongs in the Neon console and in
-- whatever the reader keeps it in, never in a script that prints its own
-- steps. ALTER DEFAULT PRIVILEGES is what keeps a table added next month
-- readable without a second grant run.
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='meetings_reader') THEN CREATE ROLE meetings_reader LOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA meetings TO meetings_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA meetings TO meetings_reader;
ALTER DEFAULT PRIVILEGES FOR ROLE neondb_owner IN SCHEMA meetings GRANT SELECT ON TABLES TO meetings_reader;
-- Removes any grant made TO this role by name. It does NOT remove USAGE on
-- public, which Postgres grants to the pseudo-role PUBLIC and no per-role
-- REVOKE can take back; verified after the first DDL run. That is acceptable
-- rather than fixed here: since Postgres 15 the public schema grants PUBLIC no
-- CREATE, this project's public schema holds nothing, and revoking from PUBLIC
-- would change the database for every other role too. If anything is ever
-- created in public, it needs its own revoke.
REVOKE ALL ON SCHEMA public FROM meetings_reader;
